
// Supabase project URL and anon key
export const SUPABASE_URL = "https://erlfsougrkzbgonumhoa.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVybGZzb3Vncmt6YmdvbnVtaG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjMyMjIsImV4cCI6MjA1NzUzOTIyMn0.TRDZlAhYRDavo4ICaEgb9EKryo4qRJDoyhlz5udr8p8";
